
#ifndef _BITSTREAM_CTX_H_
#define _BITSTREAM_CTX_H_

#ifdef __cplusplus
extern "C" {
#endif

#include "macroblock.h"


enum {
	CTX_MB_SKIP_FLAG = 0,
	CTX_MB_FIELD_DECODING_FLAG,
	CTX_MB_TYPE,
	CTX_TRANSFORM_SIZE_8X8_FLAG,
	CTX_CODED_BLOCK_PATTERN_LUMA,
	CTX_CODED_BLOCK_PATTERN_CHROMA,
	CTX_MB_QP_DELTA,
	CTX_PREV_INTRA4x4_PRED_MODE_FLAG,
	CTX_REM_INTRA4X4_PRED_MODE,
	CTX_PREV_INTRA8x8_PRED_MODE_FLAG,
	CTX_REM_INTRA8X8_PRED_MODE,
	CTX_INTRA_CHROMA_PRED_MODE,
	CTX_REF_IDX_L0,
	CTX_REF_IDX_L1,
	CTX_MVD_L0___0,
	CTX_MVD_L1___0,
	CTX_MVD_L0___1,
	CTX_MVD_L1___1,
	CTX_SUB_MB_TYPE,
	CTX_CODED_BLOCK_FLAG,
	CTX_SIGNIFICANT_COEFF_FLAG,
	CTX_LAST_SIGNIFICANT_COEFF_FLAG,
	CTX_COEFF_ABS_LEVEL_MINUS1
};


int getSE(mb_t *currMB, int type);


#ifdef __cplusplus
}
#endif

#endif /* _BITSTREAM_CTX_H_ */
